Bump golang.org/x/net to 0.9.0
rancher/aks-operator pull request #173
Opened 2023-04-11 08:19 UTC by furkatgofurov7

Supersedes https://github.com/rancher/aks-operator/pull/172 because we need to manually fix lint issues reported in dependabot PR. 

Signed-off by: Furkat Gofurov (furkat.gofurov@suse.com)

2023-04-11 08:46 UTC, mjura requested changes
Could you please split it into two PR's ? 
1. "Bump golang.org/x/net to 0.9.0"
2. Aks credentials fix

2023-04-11 09:08 UTC, furkatgofurov7 commented
> Could you please split it into two PR's ?
> 
> 1. "Bump golang.org/x/net to 0.9.0"
> 2. Aks credentials fix

@mjura done. 

We need to either merge https://github.com/rancher/aks-operator/pull/174 or https://github.com/rancher/aks-operator/pull/171 to make CI happy here before taking this PR in.

2023-04-14 11:09 UTC, furkatgofurov7 commented
#174 is merged, is there an easy way to rerun the failing jobs here?

2023-04-14 11:25 UTC, alexander-demicev approved these changes

2023-04-14 11:38 UTC, merged