Add unit test Test_generateUniqueLogWorkspace
rancher/aks-operator pull request #23
Opened 2021-06-04 10:35 UTC by mjura

Result from `go test`
```
PASS
ok  	github.com/rancher/aks-operator/pkg/aks	0.008s
```

2021-06-04 16:11 UTC, cmurphy requested changes
Could this be added to the CI? https://github.com/rancher/aks-operator/blob/master/scripts/validate

2021-06-05 07:55 UTC, mjura commented
> Could this be added to the CI? https://github.com/rancher/aks-operator/blob/master/scripts/validate

Thank you, good point. I have added `go test` to scritps

2021-06-06 02:20 UTC, rmweir approved these changes
LGTM, nice to see unit tests!

2021-06-07 15:48 UTC, cmurphy approved these changes

2021-06-08 05:48 UTC, merged