Improve securityContext for operator Deployment
rancher/aks-operator pull request #604
Opened 2024-07-23 06:58 UTC by mjura

1. Restrict container from acquiring additional privileges (`securityContext.allowPrivilegeEscalation`)
2. Mount container's root filesystem as read only (`securityContext.readOnlyRootFilesystem`)
3. Ensure that container won't be started as privileged container (`securityContext.privileged`)

Issue: https://github.com/rancher/aks-operator/issues/591

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**
Issue #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits into logical changes
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests
- [ ] backport needed

2024-07-23 08:04 UTC, Danil-Grigorev submitted a review, later dismissed

2024-07-23 11:09 UTC, yiannistri requested changes
I believe these settings should be under `.spec.containers[n].securityContext` rather than `spec.securityContext`. See https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod and https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

2024-07-24 09:02 UTC, mjura commented
> I believe these settings should be under `.spec.template.spec.containers[n].securityContext` rather than `spec.template.spec.securityContext`. See https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod and https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

you are right, I discovered it after testing. thank you for pointing this

2024-07-24 09:45 UTC, yiannistri approved these changes
:shield: :ok_hand:

2024-07-24 13:46 UTC, merged