[WIP] Add support for different regions such as AzureChinaCloud
rancher/aks-operator pull request #62
Opened 2022-07-05 07:28 UTC by smallteeths

2022-07-14 01:50 UTC, Jason-ZW requested changes
Others LGTM

2022-07-14 01:50 UTC, Jason-ZW commented on pkg/aks/client.go
> +		return azure.PublicCloud
Useless `case` statement

2022-07-14 06:57 UTC, smallteeths commented
> Should also update the README.md for the new secret data entry in https://github.com/rancher/aks-operator/blob/master/README.md#5-create-aks-secret-with-clientid-and-clientsecret.

PR updated.

2022-07-19 02:29 UTC, Jason-ZW approved these changes

2022-07-19 02:30 UTC, Jason-ZW approved these changes
LGTM

2023-02-13 09:04 UTC, mjura commented
Could you please rebase ?

2023-02-21 08:38 UTC, mjura commented
It will be reworked in https://github.com/rancher/aks-operator/pull/136

2023-02-21 08:38 UTC, closed without merging